#!/bin/bash

if [[ -z "$1" || -z "$2" ]]; then
    echo "Usage: $0 <namespace> <path-to-pem>"
    exit 1
fi

ssl_cert=$(cat "$2")
if [[ -z "$ssl_cert" ]]; then
    echo "Error: could not read certificate from $2"
    exit 1
fi

kubectl get configmap conjur-connect -n "$1" -o yaml | \
    sed -e "s|CONJUR_SSL_CERTIFICATE:.*|CONJUR_SSL_CERTIFICATE: |-
$ssl_cert|" | \
    kubectl apply -f -

kubctl get configmap conjur-connect-jwt -n "$1" -o yaml | \
    sed -e "s|CONJUR_SSL_CERTIFICATE:.*|CONJUR_SSL_CERTIFICATE: |-
$ssl_cert|" | \
    kubectl apply -f -