---
apiVersion: v1
kind: Namespace
metadata:
  name: summon-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: summon-app-account
  namespace: summon-app
---
apiVersion: v1
kind: Service
metadata:
  name: summon-app-service
  namespace: summon-app
spec:
  type: LoadBalancer
  selector:
    app: summon-app
  ports:
    - protocol: TCP
      port: 3032
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summon-app
  namespace: summon-app
  labels:
    app: summon-app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: summon-demo
      app: summon-app
  template:
    metadata:
      labels:
        role: summon-demo
        app: summon-app
    spec:
      serviceAccountName: summon-app-account
      shareProcessNamespace: true
      containers:
      - name: authenticator
        image: cyberark/conjur-authn-k8s-client:0.23.1
        imagePullPolicy: IfNotPresent
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_APPLIANCE_URL
            value: https://conjur.joegarcia.dev/api
          - name: CONJUR_AUTHN_URL
            value: https://conjur.joegarcia.dev/api/authn-k8s/conjur-demo
          - name: CONJUR_ACCOUNT
            value: cyberarkdemo
          - name: CONJUR_VERSION
            value: '5'
          - name: CONJUR_AUTHN_LOGIN
            value: host/cd/kubernetes/summon-app
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: conjur-ssl-cert
                key: conjur_joegarcia_dev.pem
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
      - name: summon-app
        image: nfmsjoeg/summon-app
        imagePullPolicy: IfNotPresent
        env:
          - name: CONJUR_APPLIANCE_URL
            value: https://conjur.joegarcia.dev
          - name: CONJUR_ACCOUNT
            value: cyberarkdemo
          - name: CONJUR_AUTHN_TOKEN_FILE
            value: /run/conjur/access-token
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: conjur-ssl-cert
                key: conjur_joegarcia_dev.pem
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
