---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: cyberark-conjur
type: Opaque
stringData:
  conjur-map: |-
    address: cd/kubernetes/db/host
    database: cd/kubernetes/db/name
    username: cd/kubernetes/db/username
    password: cd/kubernetes/db/password
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-secrets-provider-account
  namespace: cyberark-conjur
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-access
  namespace: cyberark-conjur
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: [ "get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: cyberark-conjur
  name: secrets-access-binding
subjects:
  - kind: ServiceAccount
    namespace: cyberark-conjur
    name: k8s-secrets-provider-account
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: secrets-access
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-secrets-service
  namespace: cyberark-conjur
spec:
  type: LoadBalancer
  selector:
    app: k8ssecrets
  ports:
    - protocol: TCP
      port: 3034
      targetPort: 8080
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8ssecrets-cronjob
  namespace: cyberark-conjur
spec:
  schedule: "5 * * * *" # every 5 minutes https://crontab.guru
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: k8s-secrets-provider-account
          containers:
          - name: cyberark-secrets-provider
            image: cyberark/secrets-provider-for-k8s:latest
            imagePullPolicy: Always
            envFrom:
              configMapRef:
                name: conjur-connect
            env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CONJUR_AUTHN_LOGIN
              value: host/cd/kubernetes/k8s-secrets-app
            - name: SECRETS_DESTINATION
              value: k8s_secrets
            - name: K8S_SECRETS
              value: db-credentials
          restartPolicy: OnFailure
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8ssecrets-demo
  namespace: cyberark-conjur
  labels:
    app: k8ssecrets
spec:
  replicas: 1
  selector:
    matchLabels:
      role: demo
      app: k8ssecrets
  template:
    metadata:
      labels:
        role: demo
        app: k8ssecrets
    spec:
      containers:
      - name: k8s-secrets-app
        image: nfmsjoeg/k8s-secrets-app-80251e73f499bafd2533f84946cc1c80
        imagePullPolicy: Always
        env:
          - name: DB_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: address
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: database
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
